# Generated by Django 2.0.3 on 2020-04-11 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JieBaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=256, verbose_name='关键字')),
                ('weight_count', models.IntegerField(verbose_name='频率')),
            ],
        ),
        migrations.CreateModel(
            name='JobComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '职位评论',
                'verbose_name_plural': '职位评论',
                'db_table': 'job_comment',
            },
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('company_type', models.CharField(max_length=200, verbose_name='公司类别')),
                ('company_industry', models.CharField(max_length=200, verbose_name='公司行业')),
                ('company_location', models.CharField(max_length=200, verbose_name='公司地址')),
                ('company_address', models.CharField(max_length=255, verbose_name='联系地址（具体)')),
                ('company_info', models.TextField(verbose_name='公司详情信息')),
                ('job_title', models.CharField(max_length=200, verbose_name='职位标题')),
                ('job_type', models.CharField(max_length=200, verbose_name='岗位类别')),
                ('job_detail', models.TextField(verbose_name='工作详细信息')),
                ('experience', models.CharField(max_length=200, verbose_name='经验')),
                ('xueli', models.CharField(max_length=200, verbose_name='学历')),
                ('welfare', models.CharField(max_length=100, verbose_name='福利')),
                ('pub_time', models.CharField(max_length=200, verbose_name='发布时间')),
                ('salary', models.CharField(max_length=100, verbose_name='薪资水平')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='主题')),
                ('status', models.IntegerField(choices=[(0, '爬取中'), (1, '已完成')])),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='耗时')),
                ('page', models.IntegerField(verbose_name='页数')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关键字',
                'verbose_name_plural': '关键字',
            },
        ),
        migrations.CreateModel(
            name='UserCollectJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '职位收藏',
                'verbose_name_plural': '职位收藏',
                'db_table': 'job_collect',
            },
        ),
        migrations.CreateModel(
            name='UserPostJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JobModel')),
            ],
            options={
                'verbose_name': '投递职位',
                'verbose_name_plural': '投递职位',
                'db_table': 'job_post',
            },
        ),
    ]
