# Generated by Django 2.0.3 on 2020-04-11 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercollectjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.JobModel'),
        ),
        migrations.AddField(
            model_name='usercollectjob',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TaskModel'),
        ),
        migrations.AddField(
            model_name='jobcomment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.JobModel', verbose_name='评论的职位'),
        ),
        migrations.AddField(
            model_name='jobcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='jiebamodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jieba', to='app.TaskModel'),
        ),
        migrations.AlterUniqueTogether(
            name='userpostjob',
            unique_together={('user', 'job')},
        ),
        migrations.AlterIndexTogether(
            name='userpostjob',
            index_together={('user', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='usercollectjob',
            unique_together={('user', 'job')},
        ),
        migrations.AlterIndexTogether(
            name='usercollectjob',
            index_together={('user', 'job')},
        ),
    ]
