# Generated by Django 2.0.3 on 2020-06-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200413_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('locus', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='编号')),
                ('length', models.CharField(max_length=255, verbose_name='氨基酸数目')),
                ('moltype', models.CharField(max_length=255, verbose_name='分子类型')),
                ('topology', models.CharField(max_length=255, verbose_name='拓扑学形状')),
                ('division', models.CharField(max_length=255, verbose_name='分类')),
                ('update_date', models.CharField(db_column='update-date', max_length=255, verbose_name='更新日期')),
                ('create_date', models.CharField(db_column='create-date', max_length=255, verbose_name='创建日期')),
                ('primary_accession', models.CharField(db_column='primary-accession', max_length=255, verbose_name='初始版本号')),
                ('accession_version', models.CharField(db_column='accession-version', max_length=255, verbose_name='版本号')),
                ('definition', models.CharField(db_column='definition', max_length=255, verbose_name='正式名称')),
                ('other_seqids_INSDSeqid_1', models.CharField(db_column='other-seqids.INSDSeqid.1', max_length=255, verbose_name='序列编号1')),
                ('other_seqids_INSDSeqid_2', models.CharField(db_column='other-seqids.INSDSeqid.2', max_length=255, verbose_name='序列编号1')),
                ('source', models.CharField(db_column='source', max_length=255, verbose_name='序列来源')),
                ('organism', models.CharField(db_column='organism', max_length=255, verbose_name='物种名称')),
                ('taxonomy', models.CharField(db_column='taxonomy', max_length=255, verbose_name='分类')),
                ('Reference_reference_1', models.CharField(db_column='Reference_reference.1', max_length=255, verbose_name='参考文献1')),
                ('Reference_position_1', models.CharField(db_column='Reference_position.1', max_length=255, verbose_name='对应氨基酸序列位置1')),
                ('Reference_title_1', models.CharField(db_column='Reference_title.1', max_length=255, verbose_name='参考文献1名称')),
                ('Reference_journal_1', models.CharField(db_column='Reference_journal.1', max_length=255, verbose_name='参考文献期刊1')),
                ('Reference_reference_2', models.CharField(db_column='Reference_reference.2', max_length=255, verbose_name='参考文献2')),
                ('Reference_position_2', models.CharField(db_column='Reference_position.2', max_length=255, verbose_name='对应氨基酸序列位置2')),
                ('Reference_title_2', models.CharField(db_column='Reference_title.2', max_length=255, verbose_name='参考文献2名称')),
                ('Reference_journal_2', models.CharField(db_column='Reference_journal.2', max_length=255, verbose_name='参考文献期刊2')),
                ('Reference_authers_INSDAuthor_1', models.CharField(db_column='Reference_authers.INSDAuthor.1', max_length=255, verbose_name='作者1')),
                ('Reference_authers_INSDAuthor_2', models.CharField(db_column='Reference_authers.INSDAuthor.2', max_length=255, verbose_name='作者2')),
                ('Reference_authers_INSDAuthor_3', models.CharField(db_column='Reference_authers.INSDAuthor.3', max_length=255, verbose_name='作者3')),
                ('Reference_authers_INSDAuthor_4', models.CharField(db_column='Reference_authers.INSDAuthor.4', max_length=255, verbose_name='作者4')),
                ('Reference_authers_INSDAuthor_5', models.CharField(db_column='Reference_authers.INSDAuthor.5', max_length=255, verbose_name='作者5')),
                ('Reference_authers_INSDAuthor_6', models.CharField(db_column='Reference_authers.INSDAuthor.6', max_length=255, verbose_name='作者6')),
                ('Reference_Xref_dbname', models.CharField(db_column='Reference_Xref_dbname', max_length=255, verbose_name='电子期刊编码种类')),
                ('Refernce_Xref_id', models.CharField(db_column='Refernce_Xref_id', max_length=255, verbose_name='电子期刊编码')),
                ('Reference_pubmed', models.CharField(db_column='Reference_pubmed', max_length=255, verbose_name='pubmed号码')),
                ('comment', models.CharField(db_column='comment', max_length=255, verbose_name='版本号')),
                ('source_db', models.CharField(db_column='source-db', max_length=255, verbose_name='版本号')),
                ('sequence', models.CharField(db_column='sequence', max_length=5125, verbose_name='版本号')),
            ],
            options={
                'db_table': 'march22data',
            },
        ),
        migrations.RemoveField(
            model_name='jiebamodel',
            name='task',
        ),
        migrations.RemoveField(
            model_name='jobcomment',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='usercollectjob',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='usercollectjob',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='usercollectjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='usercollectjob',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userpostjob',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='userpostjob',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='userpostjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='userpostjob',
            name='user',
        ),
        migrations.DeleteModel(
            name='JieBaModel',
        ),
        migrations.DeleteModel(
            name='JobComment',
        ),
        migrations.DeleteModel(
            name='JobModel',
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
        migrations.DeleteModel(
            name='UserCollectJob',
        ),
        migrations.DeleteModel(
            name='UserPostJob',
        ),
    ]
